# Generated by Django 5.0.4 on 2024-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecasting_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300, verbose_name='City')),
                ('timezone', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('status', models.CharField(max_length=40)),
            ],
        ),
    ]
