# Generated by Django 5.0.4 on 2024-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Email_id', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=True)),
            ],
        ),
    ]
