# Generated by Django 5.0.4 on 2024-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='weatherforecasting_data',
            name='Email_id',
            field=models.EmailField(default='default_email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='weatherforecasting_data',
            name='Password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='weatherforecasting_data',
            name='Username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherforecasting_data',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
