# Generated by Django 5.0.4 on 2024-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_delete_user_weatherforecasting_data_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecasting_data',
            name='Email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='weatherforecasting_data',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
